name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Maven
      run: ./mvnw --settings ./.m2/settings.xml clean install
      env:
        queoMavenRepositoryUserName: ${{ secrets.QUEO_MAVEN_REPOSITORY_USER_NAME }}
        queoMavenRepositoryPassword: ${{ secrets.QUEO_MAVEN_REPOSITORY_PASSWORD }}
